// For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT [riscv_const.py]

// Operand type for instruction's operands

export const RISCV_OP_INVALID = 0;
export const RISCV_OP_REG = 1;
export const RISCV_OP_IMM = 2;
export const RISCV_OP_MEM = 3;

// RISCV registers

export const RISCV_REG_INVALID = 0;

// General purpose registers
export const RISCV_REG_X0 = 1;
// export const RISCV_REG_ZERO = RISCV_REG_X0
export const RISCV_REG_X1 = 2;
// export const RISCV_REG_RA = RISCV_REG_X1
export const RISCV_REG_X2 = 3;
// export const RISCV_REG_SP = RISCV_REG_X2
export const RISCV_REG_X3 = 4;
// export const RISCV_REG_GP = RISCV_REG_X3
export const RISCV_REG_X4 = 5;
// export const RISCV_REG_TP = RISCV_REG_X4
export const RISCV_REG_X5 = 6;
// export const RISCV_REG_T0 = RISCV_REG_X5
export const RISCV_REG_X6 = 7;
// export const RISCV_REG_T1 = RISCV_REG_X6
export const RISCV_REG_X7 = 8;
// export const RISCV_REG_T2 = RISCV_REG_X7
export const RISCV_REG_X8 = 9;
// export const RISCV_REG_S0 = RISCV_REG_X8
// export const RISCV_REG_FP = RISCV_REG_X8
export const RISCV_REG_X9 = 10;
// export const RISCV_REG_S1 = RISCV_REG_X9
export const RISCV_REG_X10 = 11;
// export const RISCV_REG_A0 = RISCV_REG_X10
export const RISCV_REG_X11 = 12;
// export const RISCV_REG_A1 = RISCV_REG_X11
export const RISCV_REG_X12 = 13;
// export const RISCV_REG_A2 = RISCV_REG_X12
export const RISCV_REG_X13 = 14;
// export const RISCV_REG_A3 = RISCV_REG_X13
export const RISCV_REG_X14 = 15;
// export const RISCV_REG_A4 = RISCV_REG_X14
export const RISCV_REG_X15 = 16;
// export const RISCV_REG_A5 = RISCV_REG_X15
export const RISCV_REG_X16 = 17;
// export const RISCV_REG_A6 = RISCV_REG_X16
export const RISCV_REG_X17 = 18;
// export const RISCV_REG_A7 = RISCV_REG_X17
export const RISCV_REG_X18 = 19;
// export const RISCV_REG_S2 = RISCV_REG_X18
export const RISCV_REG_X19 = 20;
// export const RISCV_REG_S3 = RISCV_REG_X19
export const RISCV_REG_X20 = 21;
// export const RISCV_REG_S4 = RISCV_REG_X20
export const RISCV_REG_X21 = 22;
// export const RISCV_REG_S5 = RISCV_REG_X21
export const RISCV_REG_X22 = 23;
// export const RISCV_REG_S6 = RISCV_REG_X22
export const RISCV_REG_X23 = 24;
// export const RISCV_REG_S7 = RISCV_REG_X23
export const RISCV_REG_X24 = 25;
// export const RISCV_REG_S8 = RISCV_REG_X24
export const RISCV_REG_X25 = 26;
// export const RISCV_REG_S9 = RISCV_REG_X25
export const RISCV_REG_X26 = 27;
// export const RISCV_REG_S10 = RISCV_REG_X26
export const RISCV_REG_X27 = 28;
// export const RISCV_REG_S11 = RISCV_REG_X27
export const RISCV_REG_X28 = 29;
// export const RISCV_REG_T3 = RISCV_REG_X28
export const RISCV_REG_X29 = 30;
// export const RISCV_REG_T4 = RISCV_REG_X29
export const RISCV_REG_X30 = 31;
// export const RISCV_REG_T5 = RISCV_REG_X30
export const RISCV_REG_X31 = 32;
// export const RISCV_REG_T6 = RISCV_REG_X31

// Floating-point registers
export const RISCV_REG_F0_32 = 33;
export const RISCV_REG_F0_64 = 34;
export const RISCV_REG_F1_32 = 35;
export const RISCV_REG_F1_64 = 36;
export const RISCV_REG_F2_32 = 37;
export const RISCV_REG_F2_64 = 38;
export const RISCV_REG_F3_32 = 39;
export const RISCV_REG_F3_64 = 40;
export const RISCV_REG_F4_32 = 41;
export const RISCV_REG_F4_64 = 42;
export const RISCV_REG_F5_32 = 43;
export const RISCV_REG_F5_64 = 44;
export const RISCV_REG_F6_32 = 45;
export const RISCV_REG_F6_64 = 46;
export const RISCV_REG_F7_32 = 47;
export const RISCV_REG_F7_64 = 48;
export const RISCV_REG_F8_32 = 49;
export const RISCV_REG_F8_64 = 50;
export const RISCV_REG_F9_32 = 51;
export const RISCV_REG_F9_64 = 52;
export const RISCV_REG_F10_32 = 53;
export const RISCV_REG_F10_64 = 54;
export const RISCV_REG_F11_32 = 55;
export const RISCV_REG_F11_64 = 56;
export const RISCV_REG_F12_32 = 57;
export const RISCV_REG_F12_64 = 58;
export const RISCV_REG_F13_32 = 59;
export const RISCV_REG_F13_64 = 60;
export const RISCV_REG_F14_32 = 61;
export const RISCV_REG_F14_64 = 62;
export const RISCV_REG_F15_32 = 63;
export const RISCV_REG_F15_64 = 64;
export const RISCV_REG_F16_32 = 65;
export const RISCV_REG_F16_64 = 66;
export const RISCV_REG_F17_32 = 67;
export const RISCV_REG_F17_64 = 68;
export const RISCV_REG_F18_32 = 69;
export const RISCV_REG_F18_64 = 70;
export const RISCV_REG_F19_32 = 71;
export const RISCV_REG_F19_64 = 72;
export const RISCV_REG_F20_32 = 73;
export const RISCV_REG_F20_64 = 74;
export const RISCV_REG_F21_32 = 75;
export const RISCV_REG_F21_64 = 76;
export const RISCV_REG_F22_32 = 77;
export const RISCV_REG_F22_64 = 78;
export const RISCV_REG_F23_32 = 79;
export const RISCV_REG_F23_64 = 80;
export const RISCV_REG_F24_32 = 81;
export const RISCV_REG_F24_64 = 82;
export const RISCV_REG_F25_32 = 83;
export const RISCV_REG_F25_64 = 84;
export const RISCV_REG_F26_32 = 85;
export const RISCV_REG_F26_64 = 86;
export const RISCV_REG_F27_32 = 87;
export const RISCV_REG_F27_64 = 88;
export const RISCV_REG_F28_32 = 89;
export const RISCV_REG_F28_64 = 90;
export const RISCV_REG_F29_32 = 91;
export const RISCV_REG_F29_64 = 92;
export const RISCV_REG_F30_32 = 93;
export const RISCV_REG_F30_64 = 94;
export const RISCV_REG_F31_32 = 95;
export const RISCV_REG_F31_64 = 96;
export const RISCV_REG_ENDING = 97;

// RISCV instruction

export const RISCV_INS_INVALID = 0;
export const RISCV_INS_ADD = 1;
export const RISCV_INS_ADDI = 2;
export const RISCV_INS_ADDIW = 3;
export const RISCV_INS_ADDW = 4;
export const RISCV_INS_AMOADD_D = 5;
export const RISCV_INS_AMOADD_D_AQ = 6;
export const RISCV_INS_AMOADD_D_AQ_RL = 7;
export const RISCV_INS_AMOADD_D_RL = 8;
export const RISCV_INS_AMOADD_W = 9;
export const RISCV_INS_AMOADD_W_AQ = 10;
export const RISCV_INS_AMOADD_W_AQ_RL = 11;
export const RISCV_INS_AMOADD_W_RL = 12;
export const RISCV_INS_AMOAND_D = 13;
export const RISCV_INS_AMOAND_D_AQ = 14;
export const RISCV_INS_AMOAND_D_AQ_RL = 15;
export const RISCV_INS_AMOAND_D_RL = 16;
export const RISCV_INS_AMOAND_W = 17;
export const RISCV_INS_AMOAND_W_AQ = 18;
export const RISCV_INS_AMOAND_W_AQ_RL = 19;
export const RISCV_INS_AMOAND_W_RL = 20;
export const RISCV_INS_AMOMAXU_D = 21;
export const RISCV_INS_AMOMAXU_D_AQ = 22;
export const RISCV_INS_AMOMAXU_D_AQ_RL = 23;
export const RISCV_INS_AMOMAXU_D_RL = 24;
export const RISCV_INS_AMOMAXU_W = 25;
export const RISCV_INS_AMOMAXU_W_AQ = 26;
export const RISCV_INS_AMOMAXU_W_AQ_RL = 27;
export const RISCV_INS_AMOMAXU_W_RL = 28;
export const RISCV_INS_AMOMAX_D = 29;
export const RISCV_INS_AMOMAX_D_AQ = 30;
export const RISCV_INS_AMOMAX_D_AQ_RL = 31;
export const RISCV_INS_AMOMAX_D_RL = 32;
export const RISCV_INS_AMOMAX_W = 33;
export const RISCV_INS_AMOMAX_W_AQ = 34;
export const RISCV_INS_AMOMAX_W_AQ_RL = 35;
export const RISCV_INS_AMOMAX_W_RL = 36;
export const RISCV_INS_AMOMINU_D = 37;
export const RISCV_INS_AMOMINU_D_AQ = 38;
export const RISCV_INS_AMOMINU_D_AQ_RL = 39;
export const RISCV_INS_AMOMINU_D_RL = 40;
export const RISCV_INS_AMOMINU_W = 41;
export const RISCV_INS_AMOMINU_W_AQ = 42;
export const RISCV_INS_AMOMINU_W_AQ_RL = 43;
export const RISCV_INS_AMOMINU_W_RL = 44;
export const RISCV_INS_AMOMIN_D = 45;
export const RISCV_INS_AMOMIN_D_AQ = 46;
export const RISCV_INS_AMOMIN_D_AQ_RL = 47;
export const RISCV_INS_AMOMIN_D_RL = 48;
export const RISCV_INS_AMOMIN_W = 49;
export const RISCV_INS_AMOMIN_W_AQ = 50;
export const RISCV_INS_AMOMIN_W_AQ_RL = 51;
export const RISCV_INS_AMOMIN_W_RL = 52;
export const RISCV_INS_AMOOR_D = 53;
export const RISCV_INS_AMOOR_D_AQ = 54;
export const RISCV_INS_AMOOR_D_AQ_RL = 55;
export const RISCV_INS_AMOOR_D_RL = 56;
export const RISCV_INS_AMOOR_W = 57;
export const RISCV_INS_AMOOR_W_AQ = 58;
export const RISCV_INS_AMOOR_W_AQ_RL = 59;
export const RISCV_INS_AMOOR_W_RL = 60;
export const RISCV_INS_AMOSWAP_D = 61;
export const RISCV_INS_AMOSWAP_D_AQ = 62;
export const RISCV_INS_AMOSWAP_D_AQ_RL = 63;
export const RISCV_INS_AMOSWAP_D_RL = 64;
export const RISCV_INS_AMOSWAP_W = 65;
export const RISCV_INS_AMOSWAP_W_AQ = 66;
export const RISCV_INS_AMOSWAP_W_AQ_RL = 67;
export const RISCV_INS_AMOSWAP_W_RL = 68;
export const RISCV_INS_AMOXOR_D = 69;
export const RISCV_INS_AMOXOR_D_AQ = 70;
export const RISCV_INS_AMOXOR_D_AQ_RL = 71;
export const RISCV_INS_AMOXOR_D_RL = 72;
export const RISCV_INS_AMOXOR_W = 73;
export const RISCV_INS_AMOXOR_W_AQ = 74;
export const RISCV_INS_AMOXOR_W_AQ_RL = 75;
export const RISCV_INS_AMOXOR_W_RL = 76;
export const RISCV_INS_AND = 77;
export const RISCV_INS_ANDI = 78;
export const RISCV_INS_AUIPC = 79;
export const RISCV_INS_BEQ = 80;
export const RISCV_INS_BGE = 81;
export const RISCV_INS_BGEU = 82;
export const RISCV_INS_BLT = 83;
export const RISCV_INS_BLTU = 84;
export const RISCV_INS_BNE = 85;
export const RISCV_INS_CSRRC = 86;
export const RISCV_INS_CSRRCI = 87;
export const RISCV_INS_CSRRS = 88;
export const RISCV_INS_CSRRSI = 89;
export const RISCV_INS_CSRRW = 90;
export const RISCV_INS_CSRRWI = 91;
export const RISCV_INS_C_ADD = 92;
export const RISCV_INS_C_ADDI = 93;
export const RISCV_INS_C_ADDI16SP = 94;
export const RISCV_INS_C_ADDI4SPN = 95;
export const RISCV_INS_C_ADDIW = 96;
export const RISCV_INS_C_ADDW = 97;
export const RISCV_INS_C_AND = 98;
export const RISCV_INS_C_ANDI = 99;
export const RISCV_INS_C_BEQZ = 100;
export const RISCV_INS_C_BNEZ = 101;
export const RISCV_INS_C_EBREAK = 102;
export const RISCV_INS_C_FLD = 103;
export const RISCV_INS_C_FLDSP = 104;
export const RISCV_INS_C_FLW = 105;
export const RISCV_INS_C_FLWSP = 106;
export const RISCV_INS_C_FSD = 107;
export const RISCV_INS_C_FSDSP = 108;
export const RISCV_INS_C_FSW = 109;
export const RISCV_INS_C_FSWSP = 110;
export const RISCV_INS_C_J = 111;
export const RISCV_INS_C_JAL = 112;
export const RISCV_INS_C_JALR = 113;
export const RISCV_INS_C_JR = 114;
export const RISCV_INS_C_LD = 115;
export const RISCV_INS_C_LDSP = 116;
export const RISCV_INS_C_LI = 117;
export const RISCV_INS_C_LUI = 118;
export const RISCV_INS_C_LW = 119;
export const RISCV_INS_C_LWSP = 120;
export const RISCV_INS_C_MV = 121;
export const RISCV_INS_C_NOP = 122;
export const RISCV_INS_C_OR = 123;
export const RISCV_INS_C_SD = 124;
export const RISCV_INS_C_SDSP = 125;
export const RISCV_INS_C_SLLI = 126;
export const RISCV_INS_C_SRAI = 127;
export const RISCV_INS_C_SRLI = 128;
export const RISCV_INS_C_SUB = 129;
export const RISCV_INS_C_SUBW = 130;
export const RISCV_INS_C_SW = 131;
export const RISCV_INS_C_SWSP = 132;
export const RISCV_INS_C_UNIMP = 133;
export const RISCV_INS_C_XOR = 134;
export const RISCV_INS_DIV = 135;
export const RISCV_INS_DIVU = 136;
export const RISCV_INS_DIVUW = 137;
export const RISCV_INS_DIVW = 138;
export const RISCV_INS_EBREAK = 139;
export const RISCV_INS_ECALL = 140;
export const RISCV_INS_FADD_D = 141;
export const RISCV_INS_FADD_S = 142;
export const RISCV_INS_FCLASS_D = 143;
export const RISCV_INS_FCLASS_S = 144;
export const RISCV_INS_FCVT_D_L = 145;
export const RISCV_INS_FCVT_D_LU = 146;
export const RISCV_INS_FCVT_D_S = 147;
export const RISCV_INS_FCVT_D_W = 148;
export const RISCV_INS_FCVT_D_WU = 149;
export const RISCV_INS_FCVT_LU_D = 150;
export const RISCV_INS_FCVT_LU_S = 151;
export const RISCV_INS_FCVT_L_D = 152;
export const RISCV_INS_FCVT_L_S = 153;
export const RISCV_INS_FCVT_S_D = 154;
export const RISCV_INS_FCVT_S_L = 155;
export const RISCV_INS_FCVT_S_LU = 156;
export const RISCV_INS_FCVT_S_W = 157;
export const RISCV_INS_FCVT_S_WU = 158;
export const RISCV_INS_FCVT_WU_D = 159;
export const RISCV_INS_FCVT_WU_S = 160;
export const RISCV_INS_FCVT_W_D = 161;
export const RISCV_INS_FCVT_W_S = 162;
export const RISCV_INS_FDIV_D = 163;
export const RISCV_INS_FDIV_S = 164;
export const RISCV_INS_FENCE = 165;
export const RISCV_INS_FENCE_I = 166;
export const RISCV_INS_FENCE_TSO = 167;
export const RISCV_INS_FEQ_D = 168;
export const RISCV_INS_FEQ_S = 169;
export const RISCV_INS_FLD = 170;
export const RISCV_INS_FLE_D = 171;
export const RISCV_INS_FLE_S = 172;
export const RISCV_INS_FLT_D = 173;
export const RISCV_INS_FLT_S = 174;
export const RISCV_INS_FLW = 175;
export const RISCV_INS_FMADD_D = 176;
export const RISCV_INS_FMADD_S = 177;
export const RISCV_INS_FMAX_D = 178;
export const RISCV_INS_FMAX_S = 179;
export const RISCV_INS_FMIN_D = 180;
export const RISCV_INS_FMIN_S = 181;
export const RISCV_INS_FMSUB_D = 182;
export const RISCV_INS_FMSUB_S = 183;
export const RISCV_INS_FMUL_D = 184;
export const RISCV_INS_FMUL_S = 185;
export const RISCV_INS_FMV_D_X = 186;
export const RISCV_INS_FMV_W_X = 187;
export const RISCV_INS_FMV_X_D = 188;
export const RISCV_INS_FMV_X_W = 189;
export const RISCV_INS_FNMADD_D = 190;
export const RISCV_INS_FNMADD_S = 191;
export const RISCV_INS_FNMSUB_D = 192;
export const RISCV_INS_FNMSUB_S = 193;
export const RISCV_INS_FSD = 194;
export const RISCV_INS_FSGNJN_D = 195;
export const RISCV_INS_FSGNJN_S = 196;
export const RISCV_INS_FSGNJX_D = 197;
export const RISCV_INS_FSGNJX_S = 198;
export const RISCV_INS_FSGNJ_D = 199;
export const RISCV_INS_FSGNJ_S = 200;
export const RISCV_INS_FSQRT_D = 201;
export const RISCV_INS_FSQRT_S = 202;
export const RISCV_INS_FSUB_D = 203;
export const RISCV_INS_FSUB_S = 204;
export const RISCV_INS_FSW = 205;
export const RISCV_INS_JAL = 206;
export const RISCV_INS_JALR = 207;
export const RISCV_INS_LB = 208;
export const RISCV_INS_LBU = 209;
export const RISCV_INS_LD = 210;
export const RISCV_INS_LH = 211;
export const RISCV_INS_LHU = 212;
export const RISCV_INS_LR_D = 213;
export const RISCV_INS_LR_D_AQ = 214;
export const RISCV_INS_LR_D_AQ_RL = 215;
export const RISCV_INS_LR_D_RL = 216;
export const RISCV_INS_LR_W = 217;
export const RISCV_INS_LR_W_AQ = 218;
export const RISCV_INS_LR_W_AQ_RL = 219;
export const RISCV_INS_LR_W_RL = 220;
export const RISCV_INS_LUI = 221;
export const RISCV_INS_LW = 222;
export const RISCV_INS_LWU = 223;
export const RISCV_INS_MRET = 224;
export const RISCV_INS_MUL = 225;
export const RISCV_INS_MULH = 226;
export const RISCV_INS_MULHSU = 227;
export const RISCV_INS_MULHU = 228;
export const RISCV_INS_MULW = 229;
export const RISCV_INS_OR = 230;
export const RISCV_INS_ORI = 231;
export const RISCV_INS_REM = 232;
export const RISCV_INS_REMU = 233;
export const RISCV_INS_REMUW = 234;
export const RISCV_INS_REMW = 235;
export const RISCV_INS_SB = 236;
export const RISCV_INS_SC_D = 237;
export const RISCV_INS_SC_D_AQ = 238;
export const RISCV_INS_SC_D_AQ_RL = 239;
export const RISCV_INS_SC_D_RL = 240;
export const RISCV_INS_SC_W = 241;
export const RISCV_INS_SC_W_AQ = 242;
export const RISCV_INS_SC_W_AQ_RL = 243;
export const RISCV_INS_SC_W_RL = 244;
export const RISCV_INS_SD = 245;
export const RISCV_INS_SFENCE_VMA = 246;
export const RISCV_INS_SH = 247;
export const RISCV_INS_SLL = 248;
export const RISCV_INS_SLLI = 249;
export const RISCV_INS_SLLIW = 250;
export const RISCV_INS_SLLW = 251;
export const RISCV_INS_SLT = 252;
export const RISCV_INS_SLTI = 253;
export const RISCV_INS_SLTIU = 254;
export const RISCV_INS_SLTU = 255;
export const RISCV_INS_SRA = 256;
export const RISCV_INS_SRAI = 257;
export const RISCV_INS_SRAIW = 258;
export const RISCV_INS_SRAW = 259;
export const RISCV_INS_SRET = 260;
export const RISCV_INS_SRL = 261;
export const RISCV_INS_SRLI = 262;
export const RISCV_INS_SRLIW = 263;
export const RISCV_INS_SRLW = 264;
export const RISCV_INS_SUB = 265;
export const RISCV_INS_SUBW = 266;
export const RISCV_INS_SW = 267;
export const RISCV_INS_UNIMP = 268;
export const RISCV_INS_URET = 269;
export const RISCV_INS_WFI = 270;
export const RISCV_INS_XOR = 271;
export const RISCV_INS_XORI = 272;
export const RISCV_INS_ENDING = 273;

// Group of RISCV instructions

export const RISCV_GRP_INVALID = 0;
export const RISCV_GRP_JUMP = 1;
export const RISCV_GRP_CALL = 2;
export const RISCV_GRP_RET = 3;
export const RISCV_GRP_INT = 4;
export const RISCV_GRP_IRET = 5;
export const RISCV_GRP_PRIVILEGE = 6;
export const RISCV_GRP_BRANCH_RELATIVE = 7;
export const RISCV_GRP_ISRV32 = 128;
export const RISCV_GRP_ISRV64 = 129;
export const RISCV_GRP_HASSTDEXTA = 130;
export const RISCV_GRP_HASSTDEXTC = 131;
export const RISCV_GRP_HASSTDEXTD = 132;
export const RISCV_GRP_HASSTDEXTF = 133;
export const RISCV_GRP_HASSTDEXTM = 134;
export const RISCV_GRP_ISRVA = 135;
export const RISCV_GRP_ISRVC = 136;
export const RISCV_GRP_ISRVD = 137;
export const RISCV_GRP_ISRVCD = 138;
export const RISCV_GRP_ISRVF = 139;
export const RISCV_GRP_ISRV32C = 140;
export const RISCV_GRP_ISRV32CF = 141;
export const RISCV_GRP_ISRVM = 142;
export const RISCV_GRP_ISRV64A = 143;
export const RISCV_GRP_ISRV64C = 144;
export const RISCV_GRP_ISRV64D = 145;
export const RISCV_GRP_ISRV64F = 146;
export const RISCV_GRP_ISRV64M = 147;
export const RISCV_GRP_ENDING = 148;
